const HelloWorldActions = {
  SAMPLE_RESPONSE_RECEIVED : 'SAMPLE_RESPONSE_RECEIVED',
  SAMPLE_INPUT_NAME_CHANGE : 'SAMPLE_INPUT_NAME_CHANGE',
  SAMPLE_INPUT_AGE_CHANGE  : 'SAMPLE_INPUT_AGE_CHANGE'
};

export default HelloWorldActions;